# Generated by Django 4.1.6 on 2023-02-11 12:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_order_alter_item_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items'
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), size=10, verbose_name='Заказ'),
        ),
    ]
